{% set name = "Orange3-WorldHappiness" %}
{% set version = "0.1.12" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_').lower() }}-{{ version }}.tar.gz
  sha256: 238e9b7bd15357d0246ff1626efc1f77a9bd2c97aa5fc89979aae3ddb3e7a5b6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - Orange3 >=3.31
    - pandas
    - pymongo
    - wbgapi
    - dnspython

test:
  imports:
    - orangecontrib.worldhappiness
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check

about:
  home: https://github.com/biolab/orange3-world-happiness
  summary: 'Orange3 add-on for accessing socioeconomic data'
  description: |
    Orange3 World Happiness add-on for the Orange3 data mining suite.
    Enables downloading of socioeconomic data from database filled 
    from various economic databases.
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE.txt
  dev_url: https://github.com/biolab/orange3-world-happiness

extra:
  recipe-maintainers:
    - NejcHirci
    - PrimozGodec
